---
title: "High clonal diversity and spatial genetic admixture in early prostate cancer and surrounding normal tissue"
Author: Luuk Harbers
date: "Last compiled on `r format(Sys.time(), '%Y-%m-%d')`"
output: bookdown::gitbook
output_dir: "docs"
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE, message = FALSE, warning = FALSE)
options(width = 60)
```

# Introduction

On this page you can find all code associated with the manuscript 'High clonal diversity and spatial genetic admixture in early prostate cancer and surrounding normal tissue'. All the individual `R Markdown` files can be found in the [github repository](https://github.com/bicrolab/scCUTseq).  

If you wish to run any of the code yourself, simply clone the repository and (interactively) run the R Markdown files. Due to the size of the processed data, the data can be downloaded from [figshare](10.6084/m9.figshare.23675517). Simply download the data and extract it in your cloned repository.

Finally, due to changes in patient labeling, the patient numbering used in the scripts and in the datasets is incremented by 1 compared to the patient numbering in the manuscript. E.g., Patient (P) 2 in the manuscript will be P3 here. 